import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            display: "flex",
            listStyleType: "none",
            justifyContent: "space-between",
            margin: "5% 10%",
          }}
        >
          <li>
            <Link href="/">Home</Link>
          </li>

          <li>
            <Link href="/img">Img</Link>
          </li>
          <li>
            <Link href="/sample">Sample</Link>
          </li>
          <li>
            <Link href="/ssg">SSG</Link>
          </li>
          <li>
            <Link href="/user/1">User/1</Link>
          </li>
          <li>
            <Link href="/client/sample">client/sample</Link>
          </li>
        </nav>
        {children}
      </body>
    </html>
  );
}
